---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install LLNG Repository KEY
  copy:
    src: rpm-gpg-key-ow2
    dest: /tmp/gpg-key-ow2
    owner: root
    group: root
    mode: 0644

- name: Import LLNG GPG KEY
  apt_key:
    file: /tmp/gpg-key-ow2
    state: present

- name: Install LLNG Debian Repository
  copy:
    src: debian_lemonldap-ng.list
    dest: /etc/apt/sources.list.d/lemonldap-ng.list
    owner: root
    group: root
    mode: 0644
  register: llng_repo

- name: Refresh Packages Cache
  apt:
    update_cache: yes
  when:
    - llng_repo is defined
    - llng_repo.changed is defined
    - llng_repo.changed

- name: Install Webserver Dependencies (1/2)
  apt:
    name:
      - apache2
      - libapache2-mod-perl2
      - libapache2-mod-fcgid
      - apt-transport-https
      - liblasso-perl
    state: present
  when: lemonldap_webserver | default('apache') in [ 'apache', 'httpd' ]

- name: Install Webserver Dependencies (2/2)
  apt:
    name:
      - nginx
      - nginx-extras
      - lemonldap-ng-fastcgi-server
      - apt-transport-https
      - liblasso-perl
    state: present
  when: lemonldap_webserver | default('apache') == 'nginx'

- name: Enable Apache
  service:
    name: apache2
    state: started
    enabled: yes
  when: lemonldap_webserver | default('apache') in [ 'apache', 'httpd' ]

- name: Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
  when: lemonldap_webserver | default('apache') == 'nginx'

- name: Install LLNG
  apt:
    name:
      - lemonldap-ng
      - lemonldap-ng-doc
    state: present
